version: '{build}'
os: Windows Server 2012
install:
  - cmd: choco install maven -y -f
build_script:
  - mvn clean install -DskipTests=true -B -V
test_script:
  - mvn test
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
